// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package queries

import (
	"context"
	"database/sql"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    project_id, user_id, task_id, action, details
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, project_id, user_id, task_id, "action", details, created_at
`

type CreateActivityParams struct {
	ProjectID int64          `json:"project_id"`
	UserID    int64          `json:"user_id"`
	TaskID    sql.NullInt64  `json:"task_id"`
	Action    string         `json:"action"`
	Details   sql.NullString `json:"details"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.ProjectID,
		arg.UserID,
		arg.TaskID,
		arg.Action,
		arg.Details,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.TaskID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getActivity = `-- name: GetActivity :one
SELECT 
    a.id, a.project_id, a.user_id, a.task_id, a."action", a.details, a.created_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE a.id = ? LIMIT 1
`

type GetActivityRow struct {
	ID            int64          `json:"id"`
	ProjectID     int64          `json:"project_id"`
	UserID        int64          `json:"user_id"`
	TaskID        sql.NullInt64  `json:"task_id"`
	Action        string         `json:"action"`
	Details       sql.NullString `json:"details"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) GetActivity(ctx context.Context, id int64) (GetActivityRow, error) {
	row := q.db.QueryRowContext(ctx, getActivity, id)
	var i GetActivityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.TaskID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listActivitiesByProject = `-- name: ListActivitiesByProject :many
SELECT 
    a.id, a.project_id, a.user_id, a.task_id, a."action", a.details, a.created_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE a.project_id = ?
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListActivitiesByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

type ListActivitiesByProjectRow struct {
	ID            int64          `json:"id"`
	ProjectID     int64          `json:"project_id"`
	UserID        int64          `json:"user_id"`
	TaskID        sql.NullInt64  `json:"task_id"`
	Action        string         `json:"action"`
	Details       sql.NullString `json:"details"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListActivitiesByProject(ctx context.Context, arg ListActivitiesByProjectParams) ([]ListActivitiesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesByProjectRow
	for rows.Next() {
		var i ListActivitiesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.TaskID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesByTask = `-- name: ListActivitiesByTask :many
SELECT 
    a.id, a.project_id, a.user_id, a.task_id, a."action", a.details, a.created_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE a.task_id = ?
ORDER BY a.created_at DESC
`

type ListActivitiesByTaskRow struct {
	ID            int64          `json:"id"`
	ProjectID     int64          `json:"project_id"`
	UserID        int64          `json:"user_id"`
	TaskID        sql.NullInt64  `json:"task_id"`
	Action        string         `json:"action"`
	Details       sql.NullString `json:"details"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListActivitiesByTask(ctx context.Context, taskID sql.NullInt64) ([]ListActivitiesByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesByTaskRow
	for rows.Next() {
		var i ListActivitiesByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.TaskID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
