// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package queries

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (
    project_id, name, position
) VALUES (
    ?, ?, ?
)
RETURNING id, project_id, name, position, created_at, updated_at
`

type CreateBoardParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	Position  int64  `json:"position"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.ProjectID, arg.Name, arg.Position)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = ?
`

func (q *Queries) DeleteBoard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, project_id, name, position, created_at, updated_at FROM boards
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBoard(ctx context.Context, id int64) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardsByProject = `-- name: ListBoardsByProject :many
SELECT id, project_id, name, position, created_at, updated_at FROM boards
WHERE project_id = ?
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBoardsByProject(ctx context.Context, projectID int64) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoardsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET 
    name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, name, position, created_at, updated_at
`

type UpdateBoardParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard, arg.Name, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoardPosition = `-- name: UpdateBoardPosition :exec
UPDATE boards
SET 
    position = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBoardPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateBoardPosition(ctx context.Context, arg UpdateBoardPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateBoardPosition, arg.Position, arg.ID)
	return err
}
