// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checklist_items.sql

package queries

import (
	"context"
)

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (
    task_id, content, position
) VALUES (
    ?, ?, ?
)
RETURNING id, task_id, content, completed, position, created_at, updated_at
`

type CreateChecklistItemParams struct {
	TaskID   int64  `json:"task_id"`
	Content  string `json:"content"`
	Position int64  `json:"position"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, createChecklistItem, arg.TaskID, arg.Content, arg.Position)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items
WHERE id = ?
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChecklistItem, id)
	return err
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, task_id, content, completed, position, created_at, updated_at FROM checklist_items
WHERE id = ? LIMIT 1
`

func (q *Queries) GetChecklistItem(ctx context.Context, id int64) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecklistItemsByTask = `-- name: ListChecklistItemsByTask :many
SELECT id, task_id, content, completed, position, created_at, updated_at FROM checklist_items
WHERE task_id = ?
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListChecklistItemsByTask(ctx context.Context, taskID int64) ([]ChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItemsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Completed,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleChecklistItem = `-- name: ToggleChecklistItem :one
UPDATE checklist_items
SET 
    completed = NOT completed,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, task_id, content, completed, position, created_at, updated_at
`

func (q *Queries) ToggleChecklistItem(ctx context.Context, id int64) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, toggleChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE checklist_items
SET 
    content = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, task_id, content, completed, position, created_at, updated_at
`

type UpdateChecklistItemParams struct {
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistItem, arg.Content, arg.ID)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChecklistItemPosition = `-- name: UpdateChecklistItemPosition :exec
UPDATE checklist_items
SET 
    position = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChecklistItemPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateChecklistItemPosition(ctx context.Context, arg UpdateChecklistItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistItemPosition, arg.Position, arg.ID)
	return err
}
