// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package queries

import (
	"context"
	"database/sql"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (
    board_id, name, position, color, wip_limit
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, board_id, name, position, color, wip_limit, created_at, updated_at
`

type CreateColumnParams struct {
	BoardID  int64          `json:"board_id"`
	Name     string         `json:"name"`
	Position int64          `json:"position"`
	Color    sql.NullString `json:"color"`
	WipLimit sql.NullInt64  `json:"wip_limit"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.Position,
		arg.Color,
		arg.WipLimit,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.Color,
		&i.WipLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns
WHERE id = ?
`

func (q *Queries) DeleteColumn(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const getColumn = `-- name: GetColumn :one
SELECT id, board_id, name, position, color, wip_limit, created_at, updated_at FROM columns
WHERE id = ? LIMIT 1
`

func (q *Queries) GetColumn(ctx context.Context, id int64) (Column, error) {
	row := q.db.QueryRowContext(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.Color,
		&i.WipLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, name, position, color, wip_limit, created_at, updated_at FROM columns
WHERE board_id = ?
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID int64) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Column
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.Color,
			&i.WipLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET 
    name = ?,
    color = ?,
    wip_limit = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, name, position, color, wip_limit, created_at, updated_at
`

type UpdateColumnParams struct {
	Name     string         `json:"name"`
	Color    sql.NullString `json:"color"`
	WipLimit sql.NullInt64  `json:"wip_limit"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumn,
		arg.Name,
		arg.Color,
		arg.WipLimit,
		arg.ID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.Color,
		&i.WipLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColumnPosition = `-- name: UpdateColumnPosition :exec
UPDATE columns
SET 
    position = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateColumnPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnPosition, arg.Position, arg.ID)
	return err
}
