// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package queries

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    task_id, user_id, content
) VALUES (
    ?, ?, ?
)
RETURNING id, task_id, user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID  int64  `json:"task_id"`
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.TaskID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = ? AND user_id = ?
`

type DeleteCommentParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, task_id, user_id, content, created_at, updated_at FROM comments
WHERE id = ? LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentWithUser = `-- name: GetCommentWithUser :one
SELECT 
    c.id, c.task_id, c.user_id, c.content, c.created_at, c.updated_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = ? LIMIT 1
`

type GetCommentWithUserRow struct {
	ID            int64          `json:"id"`
	TaskID        int64          `json:"task_id"`
	UserID        int64          `json:"user_id"`
	Content       string         `json:"content"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) GetCommentWithUser(ctx context.Context, id int64) (GetCommentWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentWithUser, id)
	var i GetCommentWithUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT 
    c.id, c.task_id, c.user_id, c.content, c.created_at, c.updated_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.task_id = ?
ORDER BY c.created_at ASC
`

type ListCommentsByTaskRow struct {
	ID            int64          `json:"id"`
	TaskID        int64          `json:"task_id"`
	UserID        int64          `json:"user_id"`
	Content       string         `json:"content"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID int64) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByTaskRow
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET 
    content = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, task_id, user_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	Content string `json:"content"`
	ID      int64  `json:"id"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.Content, arg.ID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
