// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package queries

import (
	"context"
)

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (
    project_id, name, color
) VALUES (
    ?, ?, ?
)
RETURNING id, project_id, name, color, created_at
`

type CreateLabelParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel, arg.ProjectID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels
WHERE id = ?
`

func (q *Queries) DeleteLabel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, id)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, project_id, name, color, created_at FROM labels
WHERE id = ? LIMIT 1
`

func (q *Queries) GetLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabelsByProject = `-- name: ListLabelsByProject :many
SELECT id, project_id, name, color, created_at FROM labels
WHERE project_id = ?
ORDER BY name ASC
`

func (q *Queries) ListLabelsByProject(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET 
    name = ?,
    color = ?
WHERE id = ?
RETURNING id, project_id, name, color, created_at
`

type UpdateLabelParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, updateLabel, arg.Name, arg.Color, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
