// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID        int64          `json:"id"`
	ProjectID int64          `json:"project_id"`
	UserID    int64          `json:"user_id"`
	TaskID    sql.NullInt64  `json:"task_id"`
	Action    string         `json:"action"`
	Details   sql.NullString `json:"details"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Board struct {
	ID        int64        `json:"id"`
	ProjectID int64        `json:"project_id"`
	Name      string       `json:"name"`
	Position  int64        `json:"position"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ChecklistItem struct {
	ID        int64        `json:"id"`
	TaskID    int64        `json:"task_id"`
	Content   string       `json:"content"`
	Completed sql.NullBool `json:"completed"`
	Position  int64        `json:"position"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Column struct {
	ID        int64          `json:"id"`
	BoardID   int64          `json:"board_id"`
	Name      string         `json:"name"`
	Position  int64          `json:"position"`
	Color     sql.NullString `json:"color"`
	WipLimit  sql.NullInt64  `json:"wip_limit"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Comment struct {
	ID        int64        `json:"id"`
	TaskID    int64        `json:"task_id"`
	UserID    int64        `json:"user_id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Label struct {
	ID        int64        `json:"id"`
	ProjectID int64        `json:"project_id"`
	Name      string       `json:"name"`
	Color     string       `json:"color"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Project struct {
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	Archived    sql.NullBool   `json:"archived"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID int64        `json:"project_id"`
	UserID    int64        `json:"user_id"`
	Role      string       `json:"role"`
	JoinedAt  sql.NullTime `json:"joined_at"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    int64        `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Task struct {
	ID          int64          `json:"id"`
	ColumnID    int64          `json:"column_id"`
	CreatedBy   int64          `json:"created_by"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    int64          `json:"position"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type TaskAssignee struct {
	TaskID     int64        `json:"task_id"`
	UserID     int64        `json:"user_id"`
	AssignedAt sql.NullTime `json:"assigned_at"`
}

type TaskLabel struct {
	TaskID  int64 `json:"task_id"`
	LabelID int64 `json:"label_id"`
}

type User struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
