// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package queries

import (
	"context"
	"database/sql"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects
SET 
    archived = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_id = ?
`

type ArchiveProjectParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) error {
	_, err := q.db.ExecContext(ctx, archiveProject, arg.ID, arg.OwnerID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    owner_id, name, description, color
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, owner_id, name, description, color, archived, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     int64          `json:"owner_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Color,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = ? AND owner_id = ?
`

type DeleteProjectParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.OwnerID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, name, description, color, archived, created_at, updated_at FROM projects
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectWithOwner = `-- name: GetProjectWithOwner :one
SELECT 
    p.id, p.owner_id, p.name, p.description, p.color, p.archived, p.created_at, p.updated_at,
    u.id as owner_id,
    u.name as owner_name,
    u.email as owner_email
FROM projects p
JOIN users u ON p.owner_id = u.id
WHERE p.id = ? LIMIT 1
`

type GetProjectWithOwnerRow struct {
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	Archived    sql.NullBool   `json:"archived"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	OwnerID_2   int64          `json:"owner_id_2"`
	OwnerName   string         `json:"owner_name"`
	OwnerEmail  string         `json:"owner_email"`
}

func (q *Queries) GetProjectWithOwner(ctx context.Context, id int64) (GetProjectWithOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectWithOwner, id)
	var i GetProjectWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID_2,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const listProjectsByMember = `-- name: ListProjectsByMember :many
SELECT p.id, p.owner_id, p.name, p.description, p.color, p.archived, p.created_at, p.updated_at FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = ? AND p.archived = FALSE
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsByMember(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, name, description, color, archived, created_at, updated_at FROM projects
WHERE owner_id = ? AND archived = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveProject = `-- name: UnarchiveProject :exec
UPDATE projects
SET 
    archived = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_id = ?
`

type UnarchiveProjectParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) error {
	_, err := q.db.ExecContext(ctx, unarchiveProject, arg.ID, arg.OwnerID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET 
    name = ?,
    description = ?,
    color = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_id = ?
RETURNING id, owner_id, name, description, color, archived, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
