// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package queries

import (
	"context"
	"database/sql"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (
    project_id, user_id, role
) VALUES (
    ?, ?, ?
)
RETURNING project_id, user_id, role, joined_at
`

type AddProjectMemberParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, joined_at FROM project_members
WHERE project_id = ? AND user_id = ? LIMIT 1
`

type GetProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS(
    SELECT 1 FROM project_members
    WHERE project_id = ? AND user_id = ?
) as is_member
`

type IsProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var is_member int64
	err := row.Scan(&is_member)
	return is_member, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT 
    pm.project_id, pm.user_id, pm.role, pm.joined_at,
    u.id as user_id,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = ?
ORDER BY pm.joined_at ASC
`

type ListProjectMembersRow struct {
	ProjectID     int64          `json:"project_id"`
	UserID        int64          `json:"user_id"`
	Role          string         `json:"role"`
	JoinedAt      sql.NullTime   `json:"joined_at"`
	UserID_2      int64          `json:"user_id_2"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = ? AND user_id = ?
`

type RemoveProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = ?
WHERE project_id = ? AND user_id = ?
`

type UpdateProjectMemberRoleParams struct {
	Role      string `json:"role"`
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectMemberRole, arg.Role, arg.ProjectID, arg.UserID)
	return err
}
