// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package queries

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET 
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    column_id, created_by, title, description, position, priority, due_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, column_id, created_by, title, description, position, priority, due_date, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	ColumnID    int64          `json:"column_id"`
	CreatedBy   int64          `json:"created_by"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    int64          `json:"position"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ColumnID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, column_id, created_by, title, description, position, priority, due_date, completed_at, created_at, updated_at FROM tasks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskWithCreator = `-- name: GetTaskWithCreator :one
SELECT 
    t.id, t.column_id, t.created_by, t.title, t.description, t.position, t.priority, t.due_date, t.completed_at, t.created_at, t.updated_at,
    u.id as creator_id,
    u.name as creator_name,
    u.email as creator_email,
    u.avatar_url as creator_avatar_url
FROM tasks t
JOIN users u ON t.created_by = u.id
WHERE t.id = ? LIMIT 1
`

type GetTaskWithCreatorRow struct {
	ID               int64          `json:"id"`
	ColumnID         int64          `json:"column_id"`
	CreatedBy        int64          `json:"created_by"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Position         int64          `json:"position"`
	Priority         sql.NullString `json:"priority"`
	DueDate          sql.NullTime   `json:"due_date"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	CreatorID        int64          `json:"creator_id"`
	CreatorName      string         `json:"creator_name"`
	CreatorEmail     string         `json:"creator_email"`
	CreatorAvatarUrl sql.NullString `json:"creator_avatar_url"`
}

func (q *Queries) GetTaskWithCreator(ctx context.Context, id int64) (GetTaskWithCreatorRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskWithCreator, id)
	var i GetTaskWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorName,
		&i.CreatorEmail,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const listTasksByColumn = `-- name: ListTasksByColumn :many
SELECT id, column_id, created_by, title, description, position, priority, due_date, completed_at, created_at, updated_at FROM tasks
WHERE column_id = ? AND completed_at IS NULL
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListTasksByColumn(ctx context.Context, columnID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT t.id, t.column_id, t.created_by, t.title, t.description, t.position, t.priority, t.due_date, t.completed_at, t.created_at, t.updated_at FROM tasks t
JOIN columns c ON t.column_id = c.id
JOIN boards b ON c.board_id = b.id
WHERE b.project_id = ? AND t.completed_at IS NULL
ORDER BY t.due_date ASC, t.created_at DESC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT t.id, t.column_id, t.created_by, t.title, t.description, t.position, t.priority, t.due_date, t.completed_at, t.created_at, t.updated_at FROM tasks t
JOIN task_assignees ta ON t.id = ta.task_id
WHERE ta.user_id = ? AND t.completed_at IS NULL
ORDER BY t.due_date ASC, t.created_at DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET 
    column_id = ?,
    position = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, column_id, created_by, title, description, position, priority, due_date, completed_at, created_at, updated_at
`

type MoveTaskParams struct {
	ColumnID int64 `json:"column_id"`
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, moveTask, arg.ColumnID, arg.Position, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const uncompleteTask = `-- name: UncompleteTask :exec
UPDATE tasks
SET 
    completed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UncompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, uncompleteTask, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET 
    title = ?,
    description = ?,
    priority = ?,
    due_date = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, column_id, created_by, title, description, position, priority, due_date, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks
SET 
    position = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTaskPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition, arg.Position, arg.ID)
	return err
}
