// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_labels.sql

package queries

import (
	"context"
)

const addTaskLabel = `-- name: AddTaskLabel :one
INSERT INTO task_labels (
    task_id, label_id
) VALUES (
    ?, ?
)
RETURNING task_id, label_id
`

type AddTaskLabelParams struct {
	TaskID  int64 `json:"task_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) (TaskLabel, error) {
	row := q.db.QueryRowContext(ctx, addTaskLabel, arg.TaskID, arg.LabelID)
	var i TaskLabel
	err := row.Scan(&i.TaskID, &i.LabelID)
	return i, err
}

const getTaskLabels = `-- name: GetTaskLabels :many
SELECT 
    tl.task_id, tl.label_id,
    l.id as label_id,
    l.name as label_name,
    l.color as label_color
FROM task_labels tl
JOIN labels l ON tl.label_id = l.id
WHERE tl.task_id = ?
ORDER BY l.name ASC
`

type GetTaskLabelsRow struct {
	TaskID     int64  `json:"task_id"`
	LabelID    int64  `json:"label_id"`
	LabelID_2  int64  `json:"label_id_2"`
	LabelName  string `json:"label_name"`
	LabelColor string `json:"label_color"`
}

func (q *Queries) GetTaskLabels(ctx context.Context, taskID int64) ([]GetTaskLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskLabelsRow
	for rows.Next() {
		var i GetTaskLabelsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LabelID,
			&i.LabelID_2,
			&i.LabelName,
			&i.LabelColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasTaskLabel = `-- name: HasTaskLabel :one
SELECT EXISTS(
    SELECT 1 FROM task_labels
    WHERE task_id = ? AND label_id = ?
) as has_label
`

type HasTaskLabelParams struct {
	TaskID  int64 `json:"task_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasTaskLabel, arg.TaskID, arg.LabelID)
	var has_label int64
	err := row.Scan(&has_label)
	return has_label, err
}

const removeTaskLabel = `-- name: RemoveTaskLabel :exec
DELETE FROM task_labels
WHERE task_id = ? AND label_id = ?
`

type RemoveTaskLabelParams struct {
	TaskID  int64 `json:"task_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskLabel, arg.TaskID, arg.LabelID)
	return err
}
